[package]
name = "news"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
